import type { FormEvent } from 'react'
import { formatDate, getSlaState } from '../storage'
import type { Incident, IncidentStatus } from '../types'
import { severityLabels, statusLabels } from '../types'

type IncidentDetailsProps = { incident: Incident | null; onStatusChange: (status: IncidentStatus) => void; onComment: (event: FormEvent<HTMLFormElement>) => void }

export default function IncidentDetails({ incident, onStatusChange, onComment }: IncidentDetailsProps) {
  if (!incident) return <aside className="details-panel panel-card empty-details"><span>◈</span><h3>Selecione um incidente</h3><p>Escolha um item da tabela para ver os detalhes.</p></aside>
  const sla = getSlaState(incident)
  return <aside className="details-panel panel-card"><div className="details-heading"><div><span className={`badge severity-${incident.severity}`}><i />{severityLabels[incident.severity]}</span><h2>{incident.title}</h2><p>{incident.id} · Criado {formatDate(incident.createdAt)}</p></div></div><div className="details-description"><p>{incident.description}</p></div><div className="detail-meta"><div><span>Serviço</span><strong>{incident.service}</strong></div><div><span>Responsável</span><strong>{incident.assignee}</strong></div><div><span>SLA</span><strong className={`sla ${sla.tone}`}>{sla.label}</strong></div></div><div className="status-control"><span>Status atual</span><select value={incident.status} onChange={(event) => onStatusChange(event.target.value as IncidentStatus)}>{Object.entries(statusLabels).map(([key, label]) => <option value={key} key={key}>{label}</option>)}</select></div><div className="activity"><div className="activity-header"><h3>Atividade</h3><span>{incident.comments.length} comentário{incident.comments.length === 1 ? '' : 's'}</span></div><div className="activity-list"><div className="activity-item"><span className="timeline-dot blue" /><div><strong>Incidente criado</strong><small>{formatDate(incident.createdAt)}</small></div></div>{incident.comments.map((comment) => <div className="activity-item" key={comment.id}><span className="timeline-dot purple" /><div><strong>{comment.author} comentou</strong><p>{comment.body}</p><small>{formatDate(comment.createdAt)}</small></div></div>)}</div><form className="comment-form" onSubmit={onComment}><input name="comment" placeholder="Adicionar comentário..." aria-label="Adicionar comentário" /><button aria-label="Enviar comentário">↑</button></form></div></aside>
}
